# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d616ba3889ac8ed680803ae571785ca4c3941cd4790692190c990699dc63261fa2eccb0cb8ae005eef2dc1a7d7a3588b35e122fd5c411f4e701b6ab2ebc950da

test:
  secret_key_base: 897f68dc999c11fa9f2b17239dd0d5f32df200b0b0f2399df8740eae93a9bf0e0d534536418f54f6a65e1b15a219169633330a08959c898886f82d820cf00d73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
